apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remix
  template:
    metadata:
      labels:
        app: remix
    spec:
      containers:
        - name: remix
          image: prodacrji4x.azurecr.io/remix-weather:latest
          ports:
            - containerPort: 3000
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: apiKey
